services:
    ambta_doctrine_encrypt.encryptor:
        class: Ambta\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - %ambta_doctrine_encrypt.encryptor_class_name%
            - %ambta_doctrine_encrypt.secret_key%